image: laurentdoguin/gitpod-workspace-java-couchbase

tasks:
  - init: ./gradlew bootJar -x test
    command: java -jar target/*.jar
    name: Run app
  - name: Import Couchbase sample bucket
    command: |
      gp await-port 8091
      CB_SAMPLES='["travel-sample"]' /scripts/import-sample-buckets.sh
  - name: Start Couchbase Server
    command: |
      sudo runsvdir -P /etc/service
  - name: Install JDK 17
    command: |
      yes | sdk install java

ports:
  - port: 8090-21300
    onOpen: ignore
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 7070
    visibility: public
  - port: 8091
    visibility: public
  - port: 4369
    onOpen: ignore

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
